
RED_MIN = 162
RED_MAX = 10
ORANGE_MIN = 11
ORANGE_MAX = 25
YELLOW_MIN = 26
YELLOW_MAX = 31
GREEN_MIN = 32
GREEN_MAX = 80
CYAN_MIN = 81
CYAN_MAX = 99
BLUE_MIN = 100
BLUE_MAX = 133
PURPLE_MIN = 134
PURPLE_MAX = 161

NUM_OF_RED = 180-RED_MIN+RED_MAX+1
NUM_OF_ORANGE = ORANGE_MAX-ORANGE_MIN+1
NUM_OF_YELLOW = YELLOW_MAX-YELLOW_MIN+1
NUM_OF_GREEN = GREEN_MAX-GREEN_MIN+1
NUM_OF_CYAN = CYAN_MAX-CYAN_MIN+1
NUM_OF_BLUE = BLUE_MAX-BLUE_MIN+1
NUM_OF_PURPLE = PURPLE_MAX-PURPLE_MIN+1